name: casasilas
favicon: null
layout_spectrum: 0.22992
typography_spectrum: 0.99096
title: Casa Silas B B Granada Nicaragua
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf4d9'
    - '#000000'
    - '#71d1ff'
    - '#016a92'
    - '#a00f00'
  brandStrength: 0.5
  lightness: 0.8150793227832764
  saturation: 0.9513356708921492
  rhythmicContrast: 0.779171327361837
purpose: []
